repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-ast

  - repo: https://github.com/hhatto/autopep8
    rev: v2.0.4
    hooks:
    - id: autopep8

  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    - id: reorder-python-imports

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
      args: [--max-line-length=88]
