networks:
  nginx_nginx-network:
    external: true

services:
  streamlit_cad_webapp:
    image: ghcr.io/utikpuhlik/streamlit_cad_webapp
    build:
        context: .
    container_name: taipy-cad-webapp
    env_file:
      - .env
    networks:
      - nginx_nginx-network
