name: CI - CD
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - '*'

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: Docker Image Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push app image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/utikpuhlik/streamlit_cad_webapp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
